x = int(input("Enter x1 coordiate of first no: "))
y = int(input("Enter y1 coordinate of first no: "))
z = int(input("Enter x2 coordinate of second no: "))
a = int(input("Enter y2 coordinate of second no: "))
d = (((x-z)**2)+((y-a)**2))**(0.5)
print("Your distance b/w coordinates is:", d)